- !stat
  name: check if node exporter has already be downloaded
  path: "{{ tmp_dir }}/{{ node-exporter_install }}.tar.gz"
  save: stat_node_exporter

- !shell
  name: download node_exporter
  cmd: "curl -L -O --output-dir /{{ tmp_dir }} {{ node-exporter_url }}"
  changed_when: false
  with:
    condition: (eq stat_node_exporter.exists false)

- !shell
  name: unarchive node_exporter
  cmd: "tar -xzf /{{ tmp_dir }}/{{ node-exporter_install }}.tar.gz --directory /opt/"

- !directory
  name: set owner on install dir
  path: /opt/{{ node-exporter_install }}
  attributes:
    owner: prometheus
    group: prometheus
  recurse: true

- !template
  name: add scraper config
  src: node-exporter.scrape.yml
  dest: /opt/{{ prometheus_install }}/scrapes/node-exporter.scrape.yml
  attributes:
    owner: prometheus
    group: prometheus
    mode: 0o644
  and:
    notify:
      reload prometheus config

- !template
  name: add systemd service file
  src: node-exporter.service
  dest: /etc/systemd/system/node-exporter.service
  attributes:
    owner: root
    group: root
    mode: 0o644
  and:
    notify: reload systemd

- !sd_service
  name: start node-exporter
  service: node-exporter
  started: true
  enabled: true
