- !user
  name: create user grafana
  user: grafana
  system: true
  create_home: false

- !stat
  name: check if grafana has already be downloaded
  path: "{{ tmp_dir }}/{{ grafana_install }}.linux-amd64.tar.gz"
  save: stat_grafana

- !shell
  name: download grafana
  cmd: "curl -L -O --output-dir {{ tmp_dir }} {{ grafana_url }}"
  changed_when: false
  with:
    condition: (eq stat_grafana.exists false)

- !shell
  name: unarchive grafana
  cmd: "tar -xzf /{{ tmp_dir }}/{{ grafana_install }}.linux-amd64.tar.gz --directory /opt/"

- !directory
  name: set owner on install dir
  path: /opt/{{ grafana_install }}
  attributes:
    owner: grafana
    group: grafana
  recurse: true

- !template
  name: add systemd service file
  src: grafana.service
  dest: /etc/systemd/system/grafana.service
  attributes:
    owner: root
    group: root
    mode: 0o644
  and:
    notify: restart grafana

- !sd_service
  name: start grafana
  service: grafana
  started: true
  enabled: true
