apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-datasource
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: "POST"
    editable: true
